package constant

const (
	InvalidateInputsErr = "REF.INVALIDATION_ERROR"
	ConnectionsErr      = "REF.CANNOT_CONNECT"
	NotFoundErr         = "REF.NOT_FOUND"
	AlreadyInsertedErr  = "REF.ALREADY_INSERTED"
	AccessErr           = "REF.CANNOT_ACCESS"
	InsertErr           = "REF.CANNOT_INSERT"
	ExpiredErr          = "REF.DATA_EXPIRED"
	ResponseErr         = "REF.RESPONSE_ERROR"
	WrongInformationErr = "REF.WRONG_INFORMATION"
	UpdateErr           = "REF.CANNOT_UPDATE"
	RequiredErr         = "required"
	AlphaNumErr         = "alphaNum"
	MinLengthErr        = "minLength"
	MaxLengthErr        = "maxLength"
	MinValueErr         = "minValue"
	MaxValueErr         = "maxValue"
	PhoneErr            = "phone"
	EmailErr            = "email"
	NumericErr          = "numeric"
	IntegerErr          = "integer"
	FloatErr            = "float"
	DependencyErr       = "REF.DATA_IS_DEPENDENT"
	RemoveErr           = "REF.CANNOT_REMOVE"
	UnknownErr          = "REF.SERVICE_UNKNOWN_ERROR"
	SettingErr          = "REF.CONFIG_SETTING_NOT_FOUND"
)
